# sudo docker compose -f docker-compose-v2.yaml up -d
# exec example:
# docker compose -f docker-compose-v2.yaml exec web alembic current
version: '3.8'

services:

  db:
    container_name: postgres_db_my
    image: postgres:latest
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
       - .env.docker
    # environment: # or .env file to load params
    #   POSTGRES_USER=fapi
    #   POSTGRES_PASSWORD=fapix
    #   POSTGRES_DB=fapi_db
    # environment: # or .env file to load params
    #   POSTGRES_USER=${POSTGRES_USER}
    #   POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   POSTGRES_DB=${POSTGRES_DB}
    ports:
      # - "49150:5432"  # Iternal for PgAdmin
      - "5432:5432"    # work on local connect for DBeaver!

  web:
    build:
      context: ../
    restart: always
    depends_on:
      - db
    env_file:
      - .env.docker
    volumes:
      - web_value:/proj
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
  

volumes:
  db_value:
  web_value:

# from other folder...
# sudo docker compose -f infra/docker-compose-v2.yaml up -d
# DATABASE_URL=postgresql+asyncpg://fapi:fapix@db:5432/fapi_db
