# sudo docker compose -f docker-compose-v1.yaml up -d
version: '3.8'

services:

  db:
    container_name: postgres_db_my
    image: postgres:latest
    # restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
       - .env.example
    # environment: # or .env file to load params
    #   POSTGRES_USER: fapi
    #   POSTGRES_PASSWORD: fapix
    #   POSTGRES_DB: fapi_db

    # environment: # or .env file to load params
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # - "49150:5432"  # Iternal for PgAdmin
      - "5432:5432"    # work on local connect for DBeaver!

volumes:
  db_value:


# sudo docker compose up -d
# cd to alembic.ini
# alembic upgrade head   -> create all tables

# DATABASE_URL=postgresql+asyncpg://fapi:fapix@localhost:5432/fapi_db