# sudo docker compose -f infra/docker-compose-v1.yaml up -d
version: '3.8'

services:

  db:
    container_name: postgres_db_my
    image: postgres:latest
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
       - .env.local
    ports:
      # - "49150:5432"  # Iternal for PgAdmin
      - "5432:5432"    # work on local connect for DBeaver!

volumes:
  db_value:


# sudo docker compose -f infra/docker-compose-v1.yaml up -d
# alembic upgrade head   -> create all tables

# DATABASE_URL=postgresql+asyncpg://fapi:fapix@localhost:5432/fapi_loc_db